/* this file was generated by linkcmd.xdt from the gnu.targets.arm
 * package
 */
INPUT(
    /home/anol/dvsdk/dvsdk_3_01_00_10/c6accel_1_01_00_02/soc/app/c6accel_app_config/package/cfg/c6accel_app_xv5T.ov5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/universal/lib/release/universal.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/lib/release/ce.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/alg/lib/release/Algorithm_noOS.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/alg/lib/release/alg.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/ipc/dsplink/lib/release/ipc_dsplink_3530.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/osal/linux/lib/release/osal_linux_470.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/acpy3/lib/release/acpy3.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/dman3/lib/release/dman3Cfg.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/utils/lib/release/rmm.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/utils/lib/release/smgr.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/utils/lib/release/rmmp.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/utils/lib/release/smgrmp.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/utils/lib/release/shm.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/memutils/lib/release/memutils.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/utils/xdm/lib/release/XdmUtils.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/utils/trace/lib/release/gt.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/codec_engine_2_26_01_09/packages/ti/sdo/ce/node/lib/release/node.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/local_power_manager_linux_1_24_02_09/packages/ti/bios/power/lib/release/lpm.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/dsplink_linux_1_65_00_03/packages/dsplink/gpp/export/BIN/Linux/OMAP3530/RELEASE/dsplink.lib
    /home/anol/dvsdk/dvsdk_3_01_00_10/framework_components_2_25_01_05/packages/ti/sdo/fc/scpy/lib/release/scpy.av5T
    /home/anol/dvsdk/dvsdk_3_01_00_10/linuxutils_2_25_05_11/packages/ti/sdo/linuxutils/cmem/lib/cmem.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/linuxutils_2_25_05_11/packages/ti/sdo/linuxutils/sdma/lib/sdma.a470MV
    /home/anol/dvsdk/dvsdk_3_01_00_10/xdctools_3_20_04_68/packages/gnu/targets/arm/rtsv5T/lib/gnu.targets.arm.rtsv5T.av5T
)

